	
	<div class="row">
		
		<div style="padding-top: 0px">
			<h4 style="margin-bottom:0;" class="section-title ng-binding"> <strong> Projectos </strong> </h4>
		</div>

		<div class="row nomargin material">
			<div class="col-md-12" style="background:#FFF;border:1px solid #eee;padding-bottom:30px;border-top:0;">				
				<br>
					<div class="row">			
					<!-- end ngRepeat: noticia in maisNoticias -->
					<div class="col-sm-6 ng-scope" ng-repeat="noticia in maisNoticias"><div class="row card" style="margin: 20px 0 0 0;"><div class="col-sm-4 nopadding mais-noticias-imagem" ng-style="{'background-image' : noticia.anexoPortalList[0].anexoPortalItemList[0].url ? 'url(http://www.ucm.minfin.gov.ao:80/cs/groups/public/documents/document/aw4x/mtax/~edisp/minfin1101289.png)' : 'url(app/main/img/placeholder.png)' }" style="background-image: url(&quot;http://www.ucm.minfin.gov.ao:80/cs/groups/public/documents/document/aw4x/mtax/~edisp/minfin1101289.png&quot;);"></div><div class="col-sm-8 mais-noticias-card" style="border-top:4px solid rgb(158, 158, 158);"><a ui-sref="sala-de-imprensa.noticias.cdPublicacao({ cdPublicacao: noticia.cdPublicacao, slug: (noticia.titulo | slugify) })" href="#!/sala-de-imprensa/noticias/7039/lei-dos-contratos-publicos-ministrada-a-gestores-no-namibe"><span ng-tt-chars-threshold="65" ng-text-truncate="noticia.titulo" class="titulo ng-isolate-scope">Lei dos Contratos Públicos ministrada a gestores no Namibe</span> </a><small class="ng-binding">Data: 09/12/2019 - Por: <span ng-tt-chars-threshold="17" ng-text-truncate="noticia.autor" class="ng-isolate-scope">MINFIN</span></small><br><span class="sumario ng-isolate-scope" ng-tt-chars-threshold="85" ng-text-truncate="noticia.sumario"><span class="ng-scope">O Serviço Nacional de Contratação Pública (SNCP) realizou nesta segunda-feira, 9 de D<span ng-show="!open">...</span><span class="btn-link ngTruncateToggleText" ng-click="toggleShow()" ng-show="!open"> More</span><span ng-show="open" class="ng-hide">ezembro, uma acção de formação em Contratação Pública dirigida aos Gestores públicos de diferentes organismos do Estado na província do Namibe.<span class="btn-link ngTruncateToggleText" ng-click="toggleShow()"> Less</span></span></span></span><div class="text-right"><a class="block ng-binding" ui-sref="sala-de-imprensa.noticias.cdPublicacao({ cdPublicacao: noticia.cdPublicacao, slug: (noticia.titulo | slugify) })" href="#!/sala-de-imprensa/noticias/7039/lei-dos-contratos-publicos-ministrada-a-gestores-no-namibe">Ler Mais &nbsp;<i class="fa fa-newspaper-o"></i></a></div></div></div></div>
					<!-- end ngRepeat: noticia in maisNoticias -->
					<div class="col-sm-6 ng-scope" ng-repeat="noticia in maisNoticias"><div class="row card" style="margin: 20px 0 0 0;"><div class="col-sm-4 nopadding mais-noticias-imagem" ng-style="{'background-image' : noticia.anexoPortalList[0].anexoPortalItemList[0].url ? 'url(http://www.ucm.minfin.gov.ao:80/cs/groups/public/documents/document/aw4x/mtax/~edisp/minfin1101258.jpg)' : 'url(app/main/img/placeholder.png)' }" style="background-image: url(&quot;http://www.ucm.minfin.gov.ao:80/cs/groups/public/documents/document/aw4x/mtax/~edisp/minfin1101258.jpg&quot;);"></div><div class="col-sm-8 mais-noticias-card" style="border-top:4px solid rgb(158, 158, 158);"><a ui-sref="sala-de-imprensa.noticias.cdPublicacao({ cdPublicacao: noticia.cdPublicacao, slug: (noticia.titulo | slugify) })" href="#!/sala-de-imprensa/noticias/7038/executivo-continua-comprometido-com-o-sector-social"><span ng-tt-chars-threshold="65" ng-text-truncate="noticia.titulo" class="titulo ng-isolate-scope">“Executivo continua comprometido com o sector social”</span> </a><small class="ng-binding">Data: 09/12/2019 - Por: <span ng-tt-chars-threshold="17" ng-text-truncate="noticia.autor" class="ng-isolate-scope">MINFIN</span></small><br><span class="sumario ng-isolate-scope" ng-tt-chars-threshold="85" ng-text-truncate="noticia.sumario"><span class="ng-scope">Os deputados da 1ª, 4ª e 5ª comissões da Assembleia Nacional aprovaram, nesta segunda<span ng-show="!open">...</span><span class="btn-link ngTruncateToggleText" ng-click="toggleShow()" ng-show="!open"> More</span><span ng-show="open" class="ng-hide">-feira, 9 de Dezembro, com 30 votos a favor, 4 votos contra e duas abstenções o “Relatório-Parecer Conjunto Final” e o “Projecto de Resolução  2020.<span class="btn-link ngTruncateToggleText" ng-click="toggleShow()"> Less</span></span></span></span><div class="text-right"><a class="block ng-binding" ui-sref="sala-de-imprensa.noticias.cdPublicacao({ cdPublicacao: noticia.cdPublicacao, slug: (noticia.titulo | slugify) })" href="#!/sala-de-imprensa/noticias/7038/executivo-continua-comprometido-com-o-sector-social">Ler Mais &nbsp;<i class="fa fa-newspaper-o"></i></a></div></div></div></div>
				</div>	
					<!-- end ngRepeat: noticia in maisNoticias -->
					<div class="col-sm-6 ng-scope" ng-repeat="noticia in maisNoticias"><div class="row card" style="margin: 20px 0 0 0;"><div class="col-sm-4 nopadding mais-noticias-imagem" ng-style="{'background-image' : noticia.anexoPortalList[0].anexoPortalItemList[0].url ? 'url(http://www.ucm.minfin.gov.ao:80/cs/groups/public/documents/document/aw4x/mtaw/~edisp/minfin1100854.jpg)' : 'url(app/main/img/placeholder.png)' }" style="background-image: url(&quot;http://www.ucm.minfin.gov.ao:80/cs/groups/public/documents/document/aw4x/mtaw/~edisp/minfin1100854.jpg&quot;);"></div><div class="col-sm-8 mais-noticias-card" style="border-top:4px solid rgb(158, 158, 158);"><a ui-sref="sala-de-imprensa.noticias.cdPublicacao({ cdPublicacao: noticia.cdPublicacao, slug: (noticia.titulo | slugify) })" href="#!/sala-de-imprensa/noticias/7029/sncp-beneficia-de-experiencia-portuguesa-sobre-criterios-de-adjudicacao"><span ng-tt-chars-threshold="65" ng-text-truncate="noticia.titulo" class="titulo ng-isolate-scope"><span class="ng-scope">SNCP beneficia de experiência portuguesa sobre Critérios de Adjud<span ng-show="!open">...</span><span class="btn-link ngTruncateToggleText" ng-click="toggleShow()" ng-show="!open"> More</span><span ng-show="open" class="ng-hide">icação<span class="btn-link ngTruncateToggleText" ng-click="toggleShow()"> Less</span></span></span></span> </a><small class="ng-binding">Data: 09/12/2019 - Por: <span ng-tt-chars-threshold="17" ng-text-truncate="noticia.autor" class="ng-isolate-scope">MINFIN</span></small><br><span class="sumario ng-isolate-scope" ng-tt-chars-threshold="85" ng-text-truncate="noticia.sumario"><span class="ng-scope">Quadros do Serviço Nacional da Contratação Pública (SNCP) participam, de 9 a 13 de De<span ng-show="!open">...</span><span class="btn-link ngTruncateToggleText" ng-click="toggleShow()" ng-show="!open"> More</span><span ng-show="open" class="ng-hide">zembro, numa acção de formação sobre Avaliação de Propostas e Definição dos Critérios de Adjudicação.<span class="btn-link ngTruncateToggleText" ng-click="toggleShow()"> Less</span></span></span></span><div class="text-right"><a class="block ng-binding" ui-sref="sala-de-imprensa.noticias.cdPublicacao({ cdPublicacao: noticia.cdPublicacao, slug: (noticia.titulo | slugify) })" href="#!/sala-de-imprensa/noticias/7029/sncp-beneficia-de-experiencia-portuguesa-sobre-criterios-de-adjudicacao">Ler Mais &nbsp;<i class="fa fa-newspaper-o"></i></a></div></div></div></div>
					<!-- end ngRepeat: noticia in maisNoticias -->
					<div class="col-sm-6 ng-scope" ng-repeat="noticia in maisNoticias"><div class="row card" style="margin: 20px 0 0 0;"><div class="col-sm-4 nopadding mais-noticias-imagem" ng-style="{'background-image' : noticia.anexoPortalList[0].anexoPortalItemList[0].url ? 'url(http://www.ucm.minfin.gov.ao:80/cs/groups/public/documents/document/zmlu/otuy/~edisp/minfin952393.jpg)' : 'url(app/main/img/placeholder.png)' }" style="background-image: url(&quot;http://www.ucm.minfin.gov.ao:80/cs/groups/public/documents/document/zmlu/otuy/~edisp/minfin952393.jpg&quot;);"></div><div class="col-sm-8 mais-noticias-card" style="border-top:4px solid rgb(158, 158, 158);"><a ui-sref="sala-de-imprensa.noticias.cdPublicacao({ cdPublicacao: noticia.cdPublicacao, slug: (noticia.titulo | slugify) })" href="#!/sala-de-imprensa/noticias/7022/fmi-disponibiliza-mais-247-milhoes-a-luz-do-eff"><span ng-tt-chars-threshold="65" ng-text-truncate="noticia.titulo" class="titulo ng-isolate-scope">FMI disponibiliza mais 247 milhões à luz do EFF</span> </a><small class="ng-binding">Data: 07/12/2019 - Por: <span ng-tt-chars-threshold="17" ng-text-truncate="noticia.autor" class="ng-isolate-scope">MINFIN</span></small><br><span class="sumario ng-isolate-scope" ng-tt-chars-threshold="85" ng-text-truncate="noticia.sumario"><span class="ng-scope">Em comunicado de imprensa divulgado, no passado dia 5 de Dezembro, o Fundo Monetário <span ng-show="!open">...</span><span class="btn-link ngTruncateToggleText" ng-click="toggleShow()" ng-show="!open"> More</span><span ng-show="open" class="ng-hide">Internacional anunciou a aprovação da avaliação das metas do programa EFF e, em Consequência, disponibilizou 247 milhões de dólares.<span class="btn-link ngTruncateToggleText" ng-click="toggleShow()"> Less</span></span></span></span><div class="text-right"><a class="block ng-binding" ui-sref="sala-de-imprensa.noticias.cdPublicacao({ cdPublicacao: noticia.cdPublicacao, slug: (noticia.titulo | slugify) })" href="#!/sala-de-imprensa/noticias/7022/fmi-disponibiliza-mais-247-milhoes-a-luz-do-eff">Ler Mais &nbsp;<i class="fa fa-newspaper-o"></i></a></div></div></div></div>
					
				</div>
		</div>

		<div class="row" style="margin: 0 0 20px 0;">
			<div class="col-sm-12 text-right footer-content-home">
				<a ui-sref="sala-de-imprensa.noticias" class="ng-binding" href="#!/sala-de-imprensa/noticias">Ver Todos&nbsp; 
					<i class="fa fa-chevron-right"></i>
				</a>
			</div>
		</div>

	</div>
